### ISSUE TITLE
Why is there a 256 limit of MAX_GUI_CONTROLS?

### ISSUE THREAD

**Issue by icebarf** [raysan5/rguilayout#11]
Hi! I'm designing a UI with the help of rGuiLayout. I noticed that the program was dumping core, or sometimes my controls would move away from the anchor whenever I had many controls. I noticed in `src/rguilayout.h` that the maximum number of gui controls is limited to 256, what is the rationale behind this? Does it cause slowdowns or code-gen issues if I have more than 256 controls?

I'm considering having a personal fork, where I could have more than 256 gui controls and then do my development with that version, is there anything I should be aware of before delve into the custom fork?

**Comment by raysan5** [comment]
@icebarf Considering there is no auto-layout mode, I though 256 controls is a considerable number of controls for a layout, what are you creating that requires more than 256 controls???

In any case, feel free to fork the project and increase that number as required.
