### ISSUE TITLE
Simple DrawTexture/Rectangle support

### ISSUE THREAD

**Issue by VioletaSaravia** [raysan5/rguilayout#14]
Hi! I'm using rguilayout to design the layout for a card game. On top of all the gui elements, there's also a lot of specific card placement coordinates that I'm having to type by hand. It would be nice if rguilayout had simple support for DrawRectanglePro or DrawTexture, nothing complicated, just being able to place a "Rectangle" widget somewhere on the screen as a placeholder, to save me the trouble of calculating and typing the coordinates of all the play regions in code. Would this be within the scope of rguilayout? If so, I could try to implement it myself. Thanks!

**Comment by raysan5** [comment]
`GuiDummyRec()` is catually intended for that pourpose.
