### ISSUE TITLE
Scaling is not correct

### ISSUE THREAD

**Issue by EquinoxM** [raysan5/rguilayout#17]
my laptop screen is only 768x1366 and I can't use the windows app because it goes beyond my screen height 
I tired to find a way around it but I can't and my only option is to use my phone as an extended display to be able to see it

**Comment by raysan5** [comment]
I'm afraid 1280x720 is the minimum size for this application.

**Comment by EquinoxM** [comment]
I meant that the app does not fit in my screen and the title bar is beyond my screen area for me to try to resize it to fit my screen and my work around that was to press the windows key + the arrow up key to get it to be in my screen area to be able to the the full app.
here is an image of what it looks like on my screen
![image](https://github.com/raysan5/rguilayout/assets/117537258/0030d20c-51ef-4f9a-96df-cccef3fe2e2b)

**Comment by raysan5** [comment]
@EquinoxM Thanks for the screenshot, now I see the issue. It has been reviewed in raylib and rGuiLayout window height.
