### ISSUE TITLE
TOOL_DESCRIPTION_BREAK isn't defined

### ISSUE THREAD

**Issue by FederAndInk** [raysan5/rguilayout#6]
In gui_window_about.h:250 `TOOL_DESCRIPTION_BREAK` isn't guarded by an `#ifdef`

https://github.com/raysan5/rguilayout/blob/9eec94596d6c0087c18331ec3083a31035ba03a4/src/gui_window_about.h#L249-L251

Like it is here:

https://github.com/raysan5/rguilayout/blob/9eec94596d6c0087c18331ec3083a31035ba03a4/src/gui_window_sponsor.h#L223-L229

**Comment by raysan5** [comment]
@FederAndInk Yeah, I'm aware of this issue, just reviewing my base tools template and not reviewed all tools yet, it will be fixed for next release.
