### ISSUE TITLE
Wayland build fails

### ISSUE THREAD

**Issue by FederAndInk** [raysan5/rguilayout#7]
When building for Wayland the previous flags are erased, making the build fail at link time:

https://github.com/raysan5/rguilayout/blob/9eec94596d6c0087c18331ec3083a31035ba03a4/src/Makefile#L278

the flags that are needed are set right before on line 269 (btw, -lX11 is set twice):

https://github.com/raysan5/rguilayout/blob/9eec94596d6c0087c18331ec3083a31035ba03a4/src/Makefile#L266-L279

**Comment by raysan5** [comment]
@FederAndInk Good catch! Feel free to send a PR!
